# Before you start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import scipy.stats as st
import numpy as np
import pandas as pd
import re
from scipy.stats import ttest_1samp


# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents. Please, load the data using Ironhack's database (db: employees, table: employees_advanced).

In [2]:
# Your code here:
df = pd.read_csv('Current_Employee_Names__Salaries__and_Position_Titles.csv')
df.head(3)

Name      Job Titles Department Full or Part-Time  \
0  ALLISON,  PAUL W      LIEUTENANT       FIRE                 F   
1   BRUNO,  KEVIN D        SERGEANT     POLICE                 F   
2   COOPER,  JOHN E  LIEUTENANT-EMT       FIRE                 F   

  Salary or Hourly  Typical Hours Annual Salary Hourly Rate  
0           Salary            NaN    $107790.00         NaN  
1           Salary            NaN    $104628.00         NaN  
2           Salary            NaN    $114324.00         NaN

Examine the `salaries` dataset using the `head` function below.

In [3]:
df.head(10)
df.shape

(32658, 8)

In [4]:
# Your code here:
df['Annual Salary'].head(5)


0    $107790.00
1    $104628.00
2    $114324.00
3     $76932.00
4    $111474.00
Name: Annual Salary, dtype: object

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [5]:
# Your code here:
df.isna().sum()


Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [6]:
# Your code here:
df['Salary or Hourly'].value_counts()


Salary    24775
Hourly     7883
Name: Salary or Hourly, dtype: int64

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [7]:
df['Department'].value_counts()

POLICE                   12973
FIRE                      4800
STREETS & SAN             2194
OEMC                      2044
WATER MGMNT               1878
AVIATION                  1612
TRANSPORTN                1103
GENERAL SERVICES           972
PUBLIC LIBRARY             932
FAMILY & SUPPORT           621
FINANCE                    575
HEALTH                     516
LAW                        405
CITY COUNCIL               400
BUILDINGS                  266
COMMUNITY DEVELOPMENT      214
BUSINESS AFFAIRS           168
BOARD OF ELECTION          112
DoIT                       101
PROCUREMENT                 86
MAYOR'S OFFICE              85
CITY CLERK                  85
CULTURAL AFFAIRS            76
ANIMAL CONTRL               73
HUMAN RESOURCES             68
INSPECTOR GEN               63
IPRA                        56
BUDGET & MGMT               44
ADMIN HEARNG                38
DISABILITIES                29
TREASURER                   24
HUMAN RELATIONS             17
COPA    

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [8]:
# Your code here:
h_workers = df['Hourly Rate'][(df['Salary or Hourly']=='Hourly')]
h_workers = h_workers.str.replace('$','')
h_workers = pd.to_numeric(h_workers)
h_workers = np.array(h_workers)
h_workers


C:\Users\gonza\AppData\Local\Temp/ipykernel_14012/4222089251.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  h_workers = h_workers.str.replace('$','')


array([14.51, 19.66, 46.1 , ..., 35.6 , 46.35, 48.85])

In [9]:
# Null hypothesis or H0: hourly wage = 30/hr
# Alternative hyp or H1: hourly wage != 30/hr

In [10]:
stat,pvalue = st.ttest_1samp(h_workers,30)
print('stat is  ',stat)
print('pvalue for the two-tailed test is ',pvalue)

stat is   21.003532193332216
pvalue for the one-tailed test is  2.4048011351057683e-95


In [11]:
#There P value is very low so we can reject H0 that says that the hourly worker mean is 30$

We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [12]:
# Your code here:
p_department = df['Annual Salary'][(df['Department']=='POLICE')& (df['Annual Salary'].isna()==False)]
p_department = p_department.str.replace('$','')
p_department = pd.to_numeric(p_department)
p_department = np.array(p_department)


C:\Users\gonza\AppData\Local\Temp/ipykernel_14012/2399552164.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  p_department = p_department.str.replace('$','')


In [13]:
# Null hypothesis or H0: mean salary in police depart <= 86000
# Alternative hyp or H1: mean salary in police depart > 86000

In [14]:
stat,pvalue = st.ttest_1samp(p_department, 86000)
print('stat is  ',stat)
print('pvalue for the one-tailed test is ',pvalue/2)

stat is   12.573116980151957
pvalue for the one-tailed test is  2.4100985740030478e-36


In [15]:
# we reject H0, P is low, so mean salary is higher than last year

Using the `crosstab` function, find the department that has the most hourly workers. 

In [16]:
# Your code here:
narrowdown_hrs = df[(df['Salary or Hourly']== 'Hourly')]
df_crosstab = pd.crosstab(narrowdown_hrs['Department'], narrowdown_hrs['Salary or Hourly'], margins = False)
df_crosstab

Salary or Hourly       Hourly
Department                   
ANIMAL CONTRL              16
AVIATION                 1056
BUDGET & MGMT               1
BUSINESS AFFAIRS            8
CITY CLERK                  3
CITY COUNCIL               52
COMMUNITY DEVELOPMENT       4
CULTURAL AFFAIRS           10
FAMILY & SUPPORT          300
FINANCE                    43
FIRE                        2
GENERAL SERVICES          767
HEALTH                      4
HUMAN RESOURCES             1
LAW                        44
MAYOR'S OFFICE              7
OEMC                     1212
POLICE                     32
PROCUREMENT                 4
PUBLIC LIBRARY            224
STREETS & SAN            1873
TRANSPORTN                707
TREASURER                   1
WATER MGMNT              1512

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [17]:
# Your code here:
ss_workers = df['Hourly Rate'][(df['Salary or Hourly']=='Hourly')& (df['Department']=='STREETS & SAN')]
ss_workers = ss_workers.str.replace('$','')
ss_workers = pd.to_numeric(ss_workers)
ss_workers = np.array(ss_workers)
ss_workers


C:\Users\gonza\AppData\Local\Temp/ipykernel_14012/4276981305.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  ss_workers = ss_workers.str.replace('$','')


array([35.6 , 20.77, 35.6 , ..., 36.21, 21.43, 36.21])

In [18]:
# Null hypothesis or H0: hourly wage ss_workers >= 35
# Alternative hyp or H1: hourly wage ss_workers < 35

In [19]:
stat, pval = ttest_1samp(ss_workers, 35)
print('stat is  ', stat)

print('pvalue for the one-tailed test is ', pval/2)
# we reject H0, 

stat is   -7.172610090911691
pvalue for the one-tailed test is  5.276243152130208e-13


In [20]:
#We reject the H0, so that means that street& San workers hourly wage is lower than 35

# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [21]:
# Your code here:
h_workers = df['Hourly Rate'][(df['Salary or Hourly']=='Hourly')]
h_workers = h_workers.str.replace('$','')
h_workers = pd.to_numeric(h_workers)
h_workers = np.array(h_workers)
h_workers


C:\Users\gonza\AppData\Local\Temp/ipykernel_14012/4222089251.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  h_workers = h_workers.str.replace('$','')


array([14.51, 19.66, 46.1 , ..., 35.6 , 46.35, 48.85])

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [22]:
# Your code here:
confidence_level = 0.95
degrees_freedom = len(h_workers) - 1 
sample_mean = np.mean(h_workers)
sample_standard_error = st.sem(h_workers)
confidence_interval = st.t.interval(confidence_level, degrees_freedom, sample_mean, sample_standard_error)
print( 'confidence interval is ', confidence_interval, '.' )

confidence interval is  (32.600503194325306, 33.13588143081741) .


# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [23]:
# Your code here:

